# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginPractice' do
  # Podfile
  use_frameworks!

      pod 'RxSwift',    '~> 4.0'
      pod 'RxCocoa',    '~> 4.0'
  # # RxTest and RxBlocking make the most sense in the context of unit/integration tests
  #     pod 'RxBlocking', '~> 4.0'
  #     pod 'RxTest',     '~> 4.0'

end
